name: Preview deployment

on:
  pull_request:
  push:
    branches-ignore:
      - main

env:
  POCKETBASE_URL: ${{ vars.POCKETBASE_URL }}
  SITE_URL: ${{ vars.SITE_URL }}
  BLOG_URL: ${{ vars.BLOG_URL }}
  OG_URL: ${{ vars.OG_URL }}
  NITRO_PRESET: ${{ vars.NITRO_PRESET }}
  FB_APP_ID: ${{ vars.FB_APP_ID }}

jobs:
  publish:
    runs-on: ubuntu-latest
    environment: preview
    permissions:
      contents: read
      deployments: write
    name: Publish
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Build
        run: bun run build

      - name: Publish to Cloudflare Pages
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: tanamoe
          directory: dist
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
